Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace aspnet_mvc_tempdata_enum.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System.Text.Json;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;

namespace aspnet_mvc_tempdata_enum.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        [TempData]
        public string Message { get; set; }

        [TempData]
        public StateEnum State { get; set; }

        [TempData]
        public int StateInt { get; set; }

        public string RequestCookieData { get; private set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            // Check cookie values.
            // REF: https://github.com/dotnet/aspnetcore/blob/v3.1.23/src/Mvc/Mvc.ViewFeatures/src/CookieTempDataProvider.cs#L63
            var encodedValue = Request.Cookies[".AspNetCore.Mvc.CookieTempDataProvider"];
            if (encodedValue != null)
            {
                var protectedData = WebEncoders.Base64UrlDecode(encodedValue);
                var dataProtector = this.HttpContext.RequestServices.GetDataProtector("Microsoft.AspNetCore.Mvc.CookieTempDataProviderToken.v1");
                var unprotectedData = dataProtector.Unprotect(protectedData);

                RequestCookieData = JsonSerializer.Serialize(JsonSerializer.Deserialize<object>(unprotectedData));
            }

            return Page();
        }

        public IActionResult OnGetOKHandler()
        {
            State = StateEnum.OK;
            StateInt = (int)StateEnum.OK;
            Message = "OK!!!!";

            return Redirect(Request.Path);
        }

        public IActionResult OnGetNGHandler()
        {
            State = StateEnum.NG;
            StateInt = (int)StateEnum.NG;
            Message = "NG...";

            return Redirect(Request.Path);
        }
    }

    public enum StateEnum
    {
        VIEW,
        OK,
        NG
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace aspnet_mvc_tempdata_enum.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<section>
    <p>State=@Model.State</p>
    <p>StateInt=@Model.StateInt</p>
    <p>Message=@Model.Message</p>
    <p>RequestCookieData=@Model.RequestCookieData</p>
</section>

<section>
    <a href="">Reload</a>
    <a asp-page-handler="OKHandler">OK</a>
    <a asp-page-handler="NGHandler">NG</a>
</section>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aspnet_mvc_tempdata_enum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">aspnet_mvc_tempdata_enum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - aspnet_mvc_tempdata_enum - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>